### Load And Clean The Data ###
```{r load_and_clean, warning=FALSE}

suppressMessages(require(dplyr))

train_data_file_location <- "pml-training.csv"
test_data_file_location <- "pml-testing.csv"

train_data_full <- read.csv(train_data_file_location)


attributes_to_convert_to_numeric <- setdiff(
  names(select_if(train_data_full, is.factor)),
  c("user_name", "cvtd_timestamp", "new_window", "classe")
)

train_data_full <- train_data_full %>%
  mutate_at(attributes_to_convert_to_numeric, as.character) %>%
  mutate_at(attributes_to_convert_to_numeric, as.numeric)

na_threshold = nrow(train_data_full)/2
more_than_half_na <- function(x) sum(is.na(x)) > na_threshold

attributes_to_exclude <- union(
  names(select_if(train_data_full, more_than_half_na)), 
  c("X")
)

attributes_to_exclude


train_data <- train_data_full %>%
  select(-one_of(attributes_to_exclude)) %>% 
  sample_n(100)

test_data <- train_data_full  %>%
  top_n(-10) 

head(train_data)

```

### Train The Model ###
```{r train_model, warning=FALSE, cache=TRUE}

suppressMessages(require(caret))

if(file.exists("rf_model_test.rda")) {
    load("rf_model_test.rda")
} else {
    rf_model <- train(classe ~ ., train_data, method="rf", preProcess="pca")
}

rf_model

```

### Save The Model ###
```{r save_model}

if(!file.exists("rf_model_test.rda")) {
    save(rf_model, file = "rf_model_test.rda")
} 

```

### Test The Model ###
```{r test_model, warning=FALSE, cache=TRUE}

test_data_predictions <- predict(rf_model, test_data)

confusionMatrix(test_data_predictions, test_data$classe)

```

